project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: images/Icon1.png
    background: "#2f4358"
    foreground: "#ffffff"
    search: true
    left:
      - icon: bar-chart
        text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1 (Introduction to Visual Analytics)"
            href: Hands-On_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
          - text: "Hands-on Exercise 2 (Designing Graphs to Enlighten)"
            href: Hands-On_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd  
          - text: "Hands-on Exercise 3 (Interactivity in Visual Analytics)"
            href: Hands-On_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd   
          - text: "Hands-on Exercise 4 (Fundamentals of Visual Analytics)"
            href: Hands-On_Ex/Hands-on_Ex04/Hands-on_Ex04.qmd 
          - text: "Hands-on Exercise 5 (Visual Multivariate Analysis)"
            href: Hands-On_Ex/Hands-on_Ex05/Hands-on_Ex05.qmd 
          - text: "Hands-on Exercise 7 (Visualising and Analysing Network & Text Data)"
            href: Hands-On_Ex/Hands-on_Ex07/Hands-on_Ex07.qmd
          
      - icon: graph-up
        text: "In-class Exercise"
        menu:
          - text: "In-Class Exercise 2"
            href: "https://public.tableau.com/app/profile/javier.phang/viz/In-Class_Ex02_17771005377600/Dashboard1"
          - text: "In-Class Exercise 3"
            href: "https://public.tableau.com/app/profile/javier.phang/viz/In-Class_Ex03_17777054045000/SuperStoreSalesReport"
          - text: "In-Class Exercise 3B"
            href: "https://public.tableau.com/app/profile/javier.phang/viz/In-Class_Ex03B/AgeSexPyramid"  
          - text: "In-Class Exercise 4A"
            href: "https://public.tableau.com/app/profile/javier.phang/viz/In-Class_Ex04A/DashboardAnalysis"    
          - text: "In-Class Exercise 4B"
            href: "https://public.tableau.com/app/profile/javier.phang/viz/In-Class_Ex04B/HospitalSurveyDashboard"      
          - text: "In-Class Exercise 5A"
            href: "https://public.tableau.com/app/profile/javier.phang/viz/In-Class_Ex05A/Dashboard1"
          - text: "In-Class Exercise 5B"
            href: "https://public.tableau.com/app/profile/javier.phang/viz/In-Class_Ex05B_17789166791910/AnalysisofTreemapofRegionStateandCity"  
            
      - icon: clipboard-data
        text: "Take-home Exercise"
        menu:
          - text: "Take-Home_Ex01"
            href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.qmd"
          - text: "Take-Home_Ex01_Slides"
            href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01_Slides.qmd"
          
      - icon: diagram-3
        text: "VAST-Challenge"
        menu:
          - text: "Take-Home_Ex02"
            href: "VAST_Challenge_2026/Take-Home_Ex02/Take-Home_Ex02.qmd"
      
          
      - icon: people
        text: "Group Project"
        href: "#"
        
    right:
      - href: index.qmd
        icon: house-fill
        text: Home
      - href: about.qmd
        icon: person-circle
        text: About


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

editor: visual
