project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: images/Icon1.png
    background: "#2f4358"
    foreground: "#ffffff"
    search: true
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1 (Introduction to Visual Analytics)"
            href: Hands-On_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
          - text: "Hands-on Exercise 2 (Designing Graphs to Enlighten)"
            href: Hands-On_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd  
      - text: "In-class"
        menu:
          - text: "Coming Soon"
            href: "#"
      - text: "Take-home"
        menu:
          - text: "Coming Soon"
            href: "#"
      - text: "Group Project"
        href: "#"
    right:
      - href: index.qmd
        text: "🏠 Home"
      - href: about.qmd
        text: "👤 About Me"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

editor: visual
