project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: images/Icon1.png
    background: "#2f4358"
    foreground: "#ffffff"
    search: true
    left:
      - icon: bar-chart
        text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1 (Introduction to Visual Analytics)"
            href: Hands-On_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
          - text: "Hands-on Exercise 2 (Designing Graphs to Enlighten)"
            href: Hands-On_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd  
          - text: "Hands-on Exercise 3 (Interactivity in Visual Analytics)"
            href: Hands-On_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd    
          
      - icon: graph-up
        text: "In-class"
        menu:
          - text: "Coming Soon"
            href: "#"
            
      - icon: clipboard-data
        text: "Take-home"
        menu:
          - text: "Coming Soon"
            href: "#"
            
      - icon: people
        text: "Group Project"
        href: "#"
        
    right:
      - href: index.qmd
        icon: house-fill
        text: Home
      - href: about.qmd
        icon: person-circle
        text: About


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

editor: visual
