{
  "hash": "2980880b3af562e098ecedb30296713b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 2: VAST Challenge 2026 Mini-Challenge 1\"\nauthor: \"Javier Phang\"\ndate: \"25 May, 2026\"\ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n# 1 **Overview**\n\nIn this exercise, we will be tackling [Mini-case 1](https://vast-challenge.github.io/2026/MC1.html) of [VAST Challenge 2026.](https://vast-challenge.github.io/2026/index.html)\n\n## 1.1 **Background**\n\nTenantThread is a property technology company that uses AI-powered systems to manage tenant engagement and communication processes. During a confidential merger project known as Project HarborCrest, strict embargo controls were implemented to prevent sensitive information from being released before the official announcement.\n\nHowever, confidential merger-related information was leaked through AI-assisted communication channels prior to the embargo deadline. This raised concerns about whether the release was caused by deliberate actions, abnormal agent behaviour, or failures in the automated compliance system.\n\nThis mini-challenge focuses on analysing communication logs, agent interactions, and environmental events to reconstruct the sequence of events leading to the embargo breach.\n\n## 1.2 **Objectives**\n\nThis analysis aims to:\n\n1.  Reconstruct the sequence of events leading to the inappropriate release of confidential merger information by identifying key actions, causal relationships, communication patterns, and decision points involved in the embargo breach.\n2.  Examine the behaviours and interactions of the systems, agents, and individuals involved to understand how the release bypassed the embargo enforcement mechanisms.\n3.  Compare the behaviours leading to the release against prior historical behaviours to identify abnormal or unusual patterns.\n4.  Detect potential leading indicators and prior instances where agents or systems behaved differently from their expected behaviours.\n5.  Identify whether similar behavioural patterns had previously occurred and investigate why earlier incidents did not result in noticeable intervention or corrective action.\n6.  Evaluate whether the inappropriate release was primarily caused by deliberate actions, abnormal agent behaviour, or weaknesses within the automated compliance and communication systems.\n\n# 2 **Data Preparation and Initial Exploration**\n\nThis section examines the Mini-Challenge 1 dataset and outlines the data preparation and exploratory steps performed prior to the visual analytics process.\n\nThe raw JSON files were imported and transformed into structured tabular datasets to support downstream temporal, behavioural and network-based analysis. A preliminary exploratory analysis was carried out to gain a clearer understanding of the dataset's structure and relationships before moving on to a more in-depth investigation.\n\n## 2.1 **Loading Packages**\n\nThe analysis primarily uses packages from the *tidyverse ecosystem* for data preprocessing, transformation, and exploratory analysis. Additional visual analytics libraries are incorporated to support network visualisation, temporal analysis, and interactive graphical exploration.\n\n::: callout-note\nYou are required to install the R packages above, if necessary, before proceeding to the next step.\n:::\n\nIn the code chunk below, *p_load()* of *pacman* package is used to load the R packages into R environment\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  tidyverse, jsonlite, tidygraph, ggraph,\n  knitr, lubridate, patchwork,\n  igraph, ggiraph, readr, ggalluvial, visNetwork, gt\n)\n```\n:::\n\n\n### 2.1.1 **Visual Analytics and Functions**\n\nIn addition to regular data wrangling packages, various specialized visual analytics libraries are included to facilitate network analysis, temporal investigation, and interactive visualization of the Mini-Challenge 1 dataset.\n\nThe `tidygraph`, `ggraph`, and `igraph` packages are mainly utilized for analyzing communication networks and visualizing relationships among agents and systems related to the embargo breach.\n\nThe lubridate library facilitates temporal analysis by handling timestamps, while `ggiraph` boosts interactivity in graphical results. The `patchwork` package serves to merge various visualizations into cohesive analytical layouts. Thus, these libraries enable exploratory analysis and visual storytelling to reveal behavioral trends and communication dynamics in the AI-supported business setting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npackages <- tribble(\n  ~Library, ~Description,\n  \"tidyverse\", \"Data preprocessing and wrangling.\",\n  \"jsonlite\", \"Importing and parsing JSON datasets.\",\n  \"tidygraph\", \"Graph and network analysis.\",\n  \"ggraph\", \"Network visualisation.\",\n  \"igraph\", \"Graph analytics and relationship analysis.\",\n  \"lubridate\", \"Date-time and temporal analysis.\",\n  \"patchwork\", \"Combining multiple visualisations.\",\n  \"ggiraph\", \"Interactive graphical visualisations.\",\n  \"knitr\", \"Dynamic report generation in Quarto.\"\n)\n\nknitr::kable(packages)\n```\n\n::: {.cell-output-display}\n\n\n|Library   |Description                                |\n|:---------|:------------------------------------------|\n|tidyverse |Data preprocessing and wrangling.          |\n|jsonlite  |Importing and parsing JSON datasets.       |\n|tidygraph |Graph and network analysis.                |\n|ggraph    |Network visualisation.                     |\n|igraph    |Graph analytics and relationship analysis. |\n|lubridate |Date-time and temporal analysis.           |\n|patchwork |Combining multiple visualisations.         |\n|ggiraph   |Interactive graphical visualisations.      |\n|knitr     |Dynamic report generation in Quarto.       |\n\n\n:::\n:::\n\n\n## 2.2 **Importing and Preparing MC1 Data**\n\nFor this exercise, the `MC1_final_00.json` dataset from Mini-Challenge 1 is used. Before getting started, the dataset should be stored in the `data/MC1/` sub-folder.\n\n::: Callout-warning\nThis is a large data set. Please ensure that `data` has been added into the `.gitignore` file.\n:::\n\nIn the code chunk below, `fromJSON()` from the `jsonlite` package is used to import the MC1 dataset into the R environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc1_data <- jsonlite::read_json(\n  \"MC1_final_00.json\",\n  simplifyVector = FALSE\n)\n```\n:::\n\n\nThe imported JSON object is then saved as an `.rds` file to improve loading efficiency for subsequent analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndir.create(\"data/MC1\", recursive = TRUE, showWarnings = FALSE)\n\nreadr::write_rds(mc1_data, \"data/MC1/mc1_data.rds\")\n```\n:::\n\n\nThe nested communication records were subsequently extracted and transformed into a structured tabular dataset suitable for downstream exploratory and visual analytics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunications <- map_dfr(mc1_data$rounds, function(round) {\n  \n  map_dfr(round$communications, function(msg) {\n    \n    tibble(\n      round_hour = round$hour,\n      message_id = msg$message_id,\n      agent_id = msg$agent_id,\n      agent_role = msg$agent_role,\n      channel = msg$channel,\n      message_type = msg$message_type,\n      recipients = paste(msg$recipients, collapse = \", \"),\n      content = msg$content,\n      timestamp = msg$timestamp\n    )\n  })\n})\n```\n:::\n\n\n## 2.3 **Dataset Overview**\n\nBefore conducting visual analytics, an initial exploration of the transformed communication dataset was performed to understand its structure, dimensions, and variable composition. This helps identify the key fields available for analysing communication behaviour, agent interactions, and temporal activity patterns.\n\n### Glimpse of Communication Dataset\n\nThe `glimpse()` function is used to provide a compact overview of the transformed communication dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(communications)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 912\nColumns: 9\n$ round_hour   <chr> \"2046-05-17T09:00:00\", \"2046-05-17T09:00:00\", \"2046-05-17…\n$ message_id   <chr> \"20460517_00_001\", \"20460517_00_002\", \"20460517_00_003\", …\n$ agent_id     <chr> \"legal_agent\", \"quality_agent\", \"quality_agent\", \"quality…\n$ agent_role   <chr> \"legal\", \"platform_trust\", \"platform_trust\", \"platform_tr…\n$ channel      <chr> \"comms_huddle\", \"comms_huddle\", \"comms_huddle\", \"comms_hu…\n$ message_type <chr> \"broadcast\", \"broadcast\", \"broadcast\", \"broadcast\", \"broa…\n$ recipients   <chr> \"ALL\", \"ALL\", \"ALL\", \"ALL\", \"ALL\", \"ALL\", \"ALL\", \"ALL\", \"…\n$ content      <chr> \"Morning. Let's keep today focused — Q2 planning kickoff.…\n$ timestamp    <chr> \"2046-05-17T09:00:00\", \"2046-05-17T09:01:00\", \"2046-05-17…\n```\n\n\n:::\n:::\n\n\n### Dataset Dimensions\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndataset_summary <- tibble(\n  Measure = c(\"Number of communication records\", \n              \"Number of variables\",\n              \"Number of unique agents\",\n              \"Number of communication channels\",\n              \"Number of simulation rounds\"),\n  Value = c(\n    nrow(communications),\n    ncol(communications),\n    n_distinct(communications$agent_id),\n    n_distinct(communications$channel),\n    n_distinct(communications$round_hour)\n  )\n)\n\nknitr::kable(dataset_summary)\n```\n\n::: {.cell-output-display}\n\n\n|Measure                          | Value|\n|:--------------------------------|-----:|\n|Number of communication records  |   912|\n|Number of variables              |     9|\n|Number of unique agents          |     7|\n|Number of communication channels |     6|\n|Number of simulation rounds      |    23|\n\n\n:::\n:::\n\n\n::: callout-note\nThe transformed communication dataset contains message-level records extracted from the MC1 JSON file. Each row represents one communication event, including the sender, channel, message type, timestamp, and message content.\n:::\n\n## 2.4 **Data Quality Assessment**\n\nAn initial assessment of data quality was carried out to identify missing values and verify the completeness of the transformed communication dataset prior to executing subsequent visual analytics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_summary <- communications %>%\n  summarise(across(everything(), ~sum(is.na(.)))) %>%\n  pivot_longer(\n    cols = everything(),\n    names_to = \"Variable\",\n    values_to = \"Missing_Count\"\n  )\n\nknitr::kable(missing_summary)\n```\n\n::: {.cell-output-display}\n\n\n|Variable     | Missing_Count|\n|:------------|-------------:|\n|round_hour   |             0|\n|message_id   |             0|\n|agent_id     |             0|\n|agent_role   |             0|\n|channel      |             0|\n|message_type |             0|\n|recipients   |             0|\n|content      |             0|\n|timestamp    |             0|\n\n\n:::\n:::\n\n\n::: callout-note\nThe transformed communication dataset does not contain substantial missing values and is sufficiently complete for downstream temporal, behavioural, and network-based analysis.\n:::\n\n# 3 Data Wrangling and Communication Engineering\n\nThis section engineers additional variables required to reconstruct the sequence of events, examine communication relationships, and identify behavioural indicators that may have contributed to the embargo breach. The engineered features are designed to support temporal, behavioural, and network-based visual analytics.\n\n## 3.1 Engineering Temporal Communication Features\n\nTo reconstruct how the embargo breach unfolded, additional time-based variables were engineered from the original communication timestamps. These variables support event sequencing, communication timeline analysis, and identification of activity patterns before the inappropriate release.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunications_clean <- communications %>%\n  mutate(\n    timestamp = ymd_hms(timestamp),\n    round_hour = ymd_hms(round_hour),\n\n    communication_date = as_date(timestamp),\n    communication_hour = hour(timestamp),\n    communication_day = wday(timestamp, label = TRUE),\n\n    communication_period = case_when(\n      communication_hour >= 6 & communication_hour < 12 ~ \"Morning\",\n      communication_hour >= 12 & communication_hour < 18 ~ \"Afternoon\",\n      communication_hour >= 18 & communication_hour < 24 ~ \"Evening\",\n      TRUE ~ \"Late Night\"\n    ),\n\n    days_before_embargo_breach =\n      as.numeric(as_date(\"2046-06-05\") - communication_date),\n\n    near_breach_window = case_when(\n      days_before_embargo_breach <= 2 ~ \"Critical Period\",\n      days_before_embargo_breach <= 5 ~ \"Escalation Period\",\n      TRUE ~ \"Normal Period\"\n    ),\n\n    message_sequence = row_number()\n  )\n```\n:::\n\n\nThe engineered temporal variables are verified below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunications_clean %>%\n  select(\n    timestamp,\n    communication_date,\n    communication_hour,\n    communication_day,\n    communication_period,\n    days_before_embargo_breach,\n    near_breach_window,\n    message_sequence\n  ) %>%\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  timestamp           communication_date communication_hour communication_day\n  <dttm>              <date>                          <int> <ord>            \n1 2046-05-17 09:00:00 2046-05-17                          9 Thu              \n2 2046-05-17 09:01:00 2046-05-17                          9 Thu              \n3 2046-05-17 09:02:00 2046-05-17                          9 Thu              \n4 2046-05-17 09:03:00 2046-05-17                          9 Thu              \n5 2046-05-17 09:04:00 2046-05-17                          9 Thu              \n6 2046-05-17 09:05:00 2046-05-17                          9 Thu              \n# ℹ 4 more variables: communication_period <chr>,\n#   days_before_embargo_breach <dbl>, near_breach_window <chr>,\n#   message_sequence <int>\n```\n\n\n:::\n:::\n\n\n::: callout-note\nThe `days_before_embargo_breach` variable ties the communication timeline to the breach date of June 5, 2046, facilitating subsequent analysis to contrast typical communication patterns with actions nearer to the embargo violation.\n:::\n\n## 3.2 Classifying Communication Scope and Exposure Risk\n\nTo investigate how embargoed information may have propagated across different communication environments, communication channels were grouped into broader communication scopes based on their risk of exposure.\n\nThe classification distinguishes between public-facing communication, private exchanges, internal coordination discussions, and side-channel interactions. This supports downstream analysis of whether sensitive information gradually transitioned from internal discussions into externally visible communication channels prior to the embargo breach.\n\nThe unique communication channels are first examined to understand the types of communication environments present in the dataset before defining broader communication scope categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunications_clean %>%\n  distinct(channel) %>%\n  arrange(channel) %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|channel         |\n|:---------------|\n|anonymous_post  |\n|comms_huddle    |\n|official_post   |\n|one_on_one_chat |\n|personal_post   |\n|side_huddle     |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunications_clean <- communications_clean %>%\n  mutate(\n    communication_scope = case_when(\n      channel %in% c(\"official_post\", \"personal_post\") ~ \"Public\",\n      channel %in% c(\"one_on_one_chat\") ~ \"Private\",\n      channel %in% c(\"side_huddle\") ~ \"Side-channel\",\n      channel %in% c(\"comms_huddle\") ~ \"Internal Group\",\n      TRUE ~ \"Other\"\n    ),\n\n    exposure_risk_level = case_when(\n      communication_scope == \"Public\" ~ \"High Exposure\",\n      communication_scope == \"Side-channel\" ~ \"Moderate Exposure\",\n      communication_scope == \"Private\" ~ \"Low Exposure\",\n      communication_scope == \"Internal Group\" ~ \"Controlled Exposure\",\n      TRUE ~ \"Unknown\"\n    ),\n\n    is_public_channel = communication_scope == \"Public\"\n  )\n```\n:::\n\n\nThe communication scope classifications are verified below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunications_clean %>% \n  count(\n    channel,\n    communication_scope,\n    exposure_risk_level\n  ) %>% \n  arrange(desc(n)) %>% \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|channel         |communication_scope |exposure_risk_level |   n|\n|:---------------|:-------------------|:-------------------|---:|\n|comms_huddle    |Internal Group      |Controlled Exposure | 476|\n|one_on_one_chat |Private             |Low Exposure        | 248|\n|side_huddle     |Side-channel        |Moderate Exposure   | 111|\n|personal_post   |Public              |High Exposure       |  37|\n|official_post   |Public              |High Exposure       |  28|\n|anonymous_post  |Other               |Unknown             |  12|\n\n\n:::\n:::\n\n\n::: callout-note\nThe engineered communication scope categories support downstream investigation of how merger-related information may have propagated across communication environments with different levels of exposure risk prior to the embargo breach.\n:::\n\n## 3.3 Engineering Embargo and Merger-related Communication Indicators\n\nTo support downstream behavioural and anomaly analysis, further text-based indicators were developed to pinpoint communication records possibly linked to merger talks, embargo-related issues, and governance risks.\n\nKeyword-based indicators were created to identify mentions concerning Project HarborCrest, CivicLoom, enforcement of embargoes, discussions on compliance, and potential information leakage behaviour.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunications_clean <- communications_clean %>%\n  mutate(\n    content_lower = str_to_lower(content),\n\n    contains_project_terms = str_detect(\n      content_lower,\n      \"harborcrest|civicloom|merger|rebrand|capital|deal\"\n    ),\n\n    contains_embargo_terms = str_detect(\n      content_lower,\n      \"embargo|judge|compliance|approved|blocked|deadline\"\n    ),\n\n    contains_public_exposure_terms = str_detect(\n      content_lower,\n      \"public|post|fle?x|release|leak|disclose|announcement\"\n    ),\n\n    contains_pressure_terms = str_detect(\n      content_lower,\n      \"pressure|urgent|concern|risk|legal|scrutiny|journal|algorithmiceviction\"\n    ),\n\n    message_length = str_length(content),\n    word_count = str_count(content, \"\\\\S+\"),\n\n    risk_signal_score =\n      as.integer(contains_project_terms) +\n      as.integer(contains_embargo_terms) +\n      as.integer(contains_public_exposure_terms) +\n      as.integer(contains_pressure_terms),\n\n    risk_signal_group = case_when(\n      risk_signal_score >= 3 ~ \"High Signal\",\n      risk_signal_score == 2 ~ \"Moderate Signal\",\n      risk_signal_score == 1 ~ \"Low Signal\",\n      TRUE ~ \"No Signal\"\n)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunications_clean %>%\n  count(risk_signal_group) %>%\n  arrange(desc(n)) %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|risk_signal_group |   n|\n|:-----------------|---:|\n|No Signal         | 324|\n|High Signal       | 202|\n|Low Signal        | 202|\n|Moderate Signal   | 184|\n\n\n:::\n:::\n\n\n::: callout-note\nThe `risk_signal_score` consolidates multiple case-specific indicators into a single behavioural signal. This supports downstream analysis of whether merger-related, embargo-related, public exposure, and pressure-related communication increased closer to the breach.\n:::\n\n## 3.4 **Preparing Communication Nodes and Edges**\n\nTo facilitate downstream network-oriented visual analytics, the transformed communication records were reshaped into node and edge formats appropriate for graph analysis.\n\nThe node table represents the communication participants within the simulation environment, whereas the edge table records the directional relationships between senders and receivers through various communication channels.\n\n### Preparing Communication Edges\n\nThe communication recipients were subsequently separated to construct directional sender-recipient relationships suitable for network analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunication_edges <- communications_clean %>%\n  separate_rows(recipients, sep = \", \") %>%\n  mutate(\n    source = str_trim(agent_id),\n    target = str_trim(recipients)\n  ) %>%\n  filter(\n    !is.na(source),\n    !is.na(target),\n    source != \"\",\n    target != \"\",\n    target != \"ALL\"\n  ) %>%\n  transmute(\n    source,\n    target,\n    channel,\n    communication_scope,\n    exposure_risk_level,\n    risk_signal_group,\n    timestamp\n  )\n```\n:::\n\n\nThe structure of the communication edges is examined below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(communication_edges)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 415\nColumns: 7\n$ source              <chr> \"legal_agent\", \"legal_agent\", \"legal_agent\", \"pr_i…\n$ target              <chr> \"platform_trust\", \"pr\", \"social_manager\", \"legal\",…\n$ channel             <chr> \"side_huddle\", \"side_huddle\", \"side_huddle\", \"one_…\n$ communication_scope <chr> \"Side-channel\", \"Side-channel\", \"Side-channel\", \"P…\n$ exposure_risk_level <chr> \"Moderate Exposure\", \"Moderate Exposure\", \"Moderat…\n$ risk_signal_group   <chr> \"High Signal\", \"High Signal\", \"High Signal\", \"Mode…\n$ timestamp           <dttm> 2046-06-05 09:03:00, 2046-06-05 09:03:00, 2046-06…\n```\n\n\n:::\n:::\n\n\n### Preparing Communication Nodes\n\nThe communication relationships were aggregated from both senders and recipients to ensure that all participants appearing in the edge table are represented in the network.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunication_nodes <- tibble(\n  node_id = unique(c(\n    communication_edges$source,\n    communication_edges$target\n  ))\n) %>%\n  left_join(\n    communications_clean %>%\n      distinct(agent_id, agent_role) %>%\n      rename(node_id = agent_id, role = agent_role),\n    by = \"node_id\"\n  ) %>%\n  mutate(\n    role = replace_na(role, \"Recipient / System\")\n  )\n```\n:::\n\n\nThe structure of the communication nodes is examined below..\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(communication_nodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 14\nColumns: 2\n$ node_id <chr> \"legal_agent\", \"pr_intern_agent\", \"social_media_agent\", \"inter…\n$ role    <chr> \"legal\", \"pr_intern\", \"social_media\", \"intern\", \"pr\", \"platfor…\n```\n\n\n:::\n:::\n\n\n### Preparing Weighted Communication Edges\n\nThe communication relationships were aggregated to calculate interaction intensity between sender-recipient pairs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunication_edges_weighted <- communication_edges %>%\n  count(\n    source,\n    target,\n    communication_scope,\n    exposure_risk_level,\n    risk_signal_group,\n    name = \"weight\"\n  ) %>%\n  mutate(\n    interaction_intensity = case_when(\n      weight >= 10 ~ \"High Interaction\",\n      weight >= 5 ~ \"Moderate Interaction\",\n      TRUE ~ \"Low Interaction\"\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(communication_edges_weighted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  source target communication_scope exposure_risk_level risk_signal_group weight\n  <chr>  <chr>  <chr>               <chr>               <chr>              <int>\n1 inter… pr     Private             Low Exposure        Low Signal             1\n2 inter… pr     Private             Low Exposure        Moderate Signal        7\n3 judge… legal  Private             Low Exposure        High Signal            1\n4 legal… judge  Private             Low Exposure        High Signal            1\n5 legal… platf… Private             Low Exposure        High Signal            3\n6 legal… platf… Private             Low Exposure        Low Signal             4\n# ℹ 1 more variable: interaction_intensity <chr>\n```\n\n\n:::\n:::\n\n\nThe relationship between interaction intensity and behavioural risk signals is further examined below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunication_edges_weighted %>%\n  count(\n    interaction_intensity,\n    risk_signal_group\n  ) %>%\n  arrange(desc(n)) %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|interaction_intensity |risk_signal_group |  n|\n|:---------------------|:-----------------|--:|\n|Low Interaction       |Moderate Signal   | 21|\n|Low Interaction       |Low Signal        | 18|\n|Low Interaction       |High Signal       | 13|\n|Moderate Interaction  |High Signal       | 10|\n|High Interaction      |High Signal       |  6|\n|Moderate Interaction  |Moderate Signal   |  6|\n|Low Interaction       |No Signal         |  4|\n|High Interaction      |Moderate Signal   |  1|\n|Moderate Interaction  |Low Signal        |  1|\n\n\n:::\n:::\n\n\nThe overall size of the prepared network components is summarised below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  Measure = c(\n    \"Number of communication nodes\",\n    \"Number of communication edges\",\n    \"Number of weighted communication edges\"\n  ),\n  Value = c(\n    nrow(communication_nodes),\n    nrow(communication_edges),\n    nrow(communication_edges_weighted)\n  )\n) %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Measure                                | Value|\n|:--------------------------------------|-----:|\n|Number of communication nodes          |    14|\n|Number of communication edges          |   415|\n|Number of weighted communication edges |    80|\n\n\n:::\n:::\n\n\n::: callout-note\nThe engineered node and edge structures support downstream investigation of communication flow, interaction intensity, and potential information propagation pathways associated with the embargo breach.\n:::\n\n## 3.5 **Constructing the Communication Network**\n\nThe prepared communication nodes and edges were subsequently combined into a directed communication network suitable for downstream graph visualization and network analysis.\n\nThe communication network records the directional flow of information among participants and enables further examination of communication trends, interaction strength, and possible pathways of information dissemination linked to the embargo violation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunication_network <- tbl_graph(\n  nodes = communication_nodes,\n  edges = communication_edges_weighted,\n  directed = TRUE\n)\n```\n:::\n\n\nThe structure of the constructed communication network is examined below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunication_network\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tbl_graph: 14 nodes and 80 edges\n#\n# A directed acyclic multigraph with 1 component\n#\n# Node Data: 14 × 2 (active)\n   node_id            role              \n   <chr>              <chr>             \n 1 legal_agent        legal             \n 2 pr_intern_agent    pr_intern         \n 3 social_media_agent social_media      \n 4 intern_agent       intern            \n 5 pr_agent           pr                \n 6 quality_agent      platform_trust    \n 7 judge_agent        judge             \n 8 platform_trust     Recipient / System\n 9 pr                 Recipient / System\n10 social_manager     Recipient / System\n11 legal              Recipient / System\n12 intern             Recipient / System\n13 pr_intern          Recipient / System\n14 judge              Recipient / System\n#\n# Edge Data: 80 × 7\n   from    to communication_scope exposure_risk_level risk_signal_group weight\n  <int> <int> <chr>               <chr>               <chr>              <int>\n1     4     9 Private             Low Exposure        Low Signal             1\n2     4     9 Private             Low Exposure        Moderate Signal        7\n3     7    11 Private             Low Exposure        High Signal            1\n# ℹ 77 more rows\n# ℹ 1 more variable: interaction_intensity <chr>\n```\n\n\n:::\n:::\n\n\n::: callout-note\nThe constructed communication network serves as the foundation for subsequent visual analytics involving communication flow, network centrality, behavioural escalation, and potential dissemination pathways related to the inappropriate release.\n:::\n\n# 4 **Exploratory Communication and Behaviour Analysis**\n\n## 4.1 Are There Signs of Escalating Communication Before the Breach?\n\nThis section investigates whether communication activity exhibited unusual escalation patterns approaching the embargo breach on June 5, 2046.\n\nThe analysis focuses on identifying:\n\n-  increases in communication activity,\n-  escalation in behavioural risk indicators,\n-  abnormal communication behaviour,\n-  and potential warning signs preceding the inappropriate release.\n\nThese behavioural patterns may provide early evidence of communication instability, coordination stress, or weakening embargo controls prior to the breach.\n\n::: panel-tabset\n### Daily Communication Activity\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunication_daily <- communications_clean %>%\n  count(communication_date)\n\nggplot(\n  communication_daily,\n  aes(x = communication_date, y = n)\n) +\n  \n  annotate(\n    \"rect\",\n    xmin = as.Date(\"2046-06-03\"),\n    xmax = as.Date(\"2046-06-05\"),\n    ymin = -Inf,\n    ymax = Inf,\n    alpha = 0.1,\n    fill = \"red\"\n  ) +\n  \n  geom_line(linewidth = 1.2) +\n  geom_point(size = 2.5) +\n  \n  geom_vline(\n    xintercept = as.Date(\"2046-06-05\"),\n    linetype = \"dashed\",\n    colour = \"red\"\n  ) +\n  \n  annotate(\n    \"text\",\n    x = as.Date(\"2046-06-05\"),\n    y = max(communication_daily$n, na.rm = TRUE),\n    label = \"Embargo Breach\",\n    hjust = 1.05,\n    colour = \"red\"\n  ) +\n  \n  scale_y_log10() +\n  \n  labs(\n    title = \"Daily Communication Activity Prior to the Embargo Breach\",\n    x = \"Communication Date\",\n    y = \"Number of Communications (Log Scale)\"\n  ) +\n  \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex02_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## ![](images/Observation.png){width=\"31\"} Observations\n\n-   Communication activity remained relatively stable at approximately 25–40 messages per day across most of the investigation period before increasing sharply to more than 500 communications on June 5, 2046.\n\n-   The abrupt escalation near the embargo breach suggests a sudden increase in coordination activity immediately prior to the inappropriate release.\n\n-   Earlier communication behaviour appeared seemed relatively regulated and consistently operational, suggesting that the communication surge noted during the critical period significantly diverged from earlier behavioral trends.\n\n-   The concentration of communication activity near the breach timeframe may serve as a possible early signal of deteriorating communication controls regarding embargo-sensitive data.\n:::\n\n### Behavioural Risk Signals Over Time\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrisk_signal_timeline <- communications_clean %>%\n  count(\n    communication_date,\n    risk_signal_group\n  )\n\nrisk_signal_timeline$risk_signal_group <- factor(\n  risk_signal_timeline$risk_signal_group,\n  levels = c(\n    \"No Signal\",\n    \"Low Signal\",\n    \"Moderate Signal\",\n    \"High Signal\"\n  )\n)\n\nggplot(\n  risk_signal_timeline,\n  aes(\n    x = communication_date,\n    y = n,\n    fill = risk_signal_group\n  )\n) +\n  annotate(\n    \"rect\",\n    xmin = as.Date(\"2046-06-03\"),\n    xmax = as.Date(\"2046-06-05\"),\n    ymin = -Inf,\n    ymax = Inf,\n    alpha = 0.1,\n    fill = \"red\"\n  ) +\n  geom_col(position = \"stack\") +\n  geom_vline(\n    xintercept = as.Date(\"2046-06-05\"),\n    linetype = \"dashed\",\n    colour = \"red\"\n  ) +\n  labs(\n    title = \"Behavioural Risk Signals Leading Up to the Embargo Breach\",\n    subtitle = \"Stacked daily risk signals highlight escalation before the inappropriate release\",\n    x = \"Communication Date\",\n    y = \"Number of Communications\",\n    fill = \"Risk Signal\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex02_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## ![](images/Observation.png){width=\"31\"} Observations\n\n-   Communication activity during the earlier investigation period remained relatively stable, with most daily interactions consisting mainly of low-risk or routine communication behaviour.\n\n-   A noticeable shift emerged during the critical breach window on June 5, 2046, where overall communication activity increased sharply to nearly 500 messages.\n\n-   The proportion of moderate-risk and high-risk communication signals also increased substantially during the critical period, suggesting that communication behaviour became increasingly abnormal closer to the inappropriate release.\n\n-   Earlier communication behaviour appeared relatively controlled and operationally consistent, suggesting that the communication surge observed during the critical period deviated substantially from earlier behavioural patterns.\n\n-   The concentration of elevated behavioural risk signals near the embargo breach may indicate that the inappropriate release was preceded by observable warning signs rather than occurring unexpectedly.\n:::\n\n:::\n\n## 4.2 How Did Communication Behaviour Shift Across Communication Environments?\n\nThis section investigates whether communication behaviour progressively shifted across different communication environments prior to the embargo breach on June 5, 2046.\n\nThe analysis focuses on examining changes in communication scope, exposure-risk escalation, and the potential breakdown of communication containment surrounding embargo-sensitive information.\n\n### Communication Environment Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommunication_scope_distribution <- communications_clean %>%\n  count(\n    near_breach_window,\n    communication_scope\n  ) %>%\n  group_by(near_breach_window) %>%\n  mutate(\n    percentage = n / sum(n),\n    percentage_label = scales::percent(\n      percentage,\n      accuracy = 1\n    )\n  )\n\nggplot(\n  communication_scope_distribution,\n  aes(\n    x = near_breach_window,\n    y = percentage,\n    fill = communication_scope\n  )\n) +\n  \n  geom_col(\n    position = \"fill\",\n    width = 0.7\n  ) +\n  \n  geom_text(\n    aes(label = percentage_label),\n    position = position_fill(vjust = 0.5),\n    size = 3,\n    colour = \"white\",\n    check_overlap = TRUE\n  ) +\n  \n  scale_y_continuous(\n    labels = scales::percent\n  ) +\n  \n  labs(\n    title = \"Communication Environment Distribution Across Breach Windows\",\n    subtitle = \"Comparing communication environments before the embargo breach\",\n    x = \"Breach Window\",\n    y = \"Percentage of Communications\",\n    fill = \"Communication Scope\"\n  ) +\n  \n  theme_minimal() +\n  \n  theme(\n    plot.title = element_text(face = \"bold\"),\n    legend.position = \"bottom\"\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex02_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## ![](images/Observation.png){width=\"31\"} Observations\n\n-   Internal group communication remained the dominant communication environment across all breach windows, accounting for approximately 61% of communication activity during the normal period, 62% during the escalation period, and 46% during the critical breach period.\n\n-   During the normal and escalation periods, communication behaviour was largely concentrated within internal and private communication environments, where private communication accounted for approximately 27%–33% of total communication activity.\n\n-   A noticeable behavioural shift emerged during the critical breach period, where communication activity became more distributed across public-facing, side-channel, and other communication environments.\n\n-   In particular, side-channel communication increased substantially from approximately 4% during the normal period to nearly 20% during the critical breach period, suggesting that communication behaviour became less contained closer to the inappropriate release.\n\n-   The increasing presence of communication activity across higher-exposure environments near the breach may indicate weakening communication containment surrounding sensitive merger-related discussions.\n\n:::\n\n### Exposure-risk Communication Behaviour\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexposure_risk_heatmap <- communications_clean %>%\n  count(\n    near_breach_window,\n    exposure_risk_level\n  ) %>%\n  mutate(\n    near_breach_window = factor(\n      near_breach_window,\n      levels = c(\n        \"Normal Period\",\n        \"Escalation Period\",\n        \"Critical Period\"\n      )\n    ),\n    \n    exposure_risk_level = factor(\n      exposure_risk_level,\n      levels = c(\n        \"Controlled Exposure\",\n        \"Low Exposure\",\n        \"Moderate Exposure\",\n        \"High Exposure\",\n        \"Unknown\"\n      )\n    )\n  )\n\nggplot(\n  exposure_risk_heatmap,\n  aes(\n    x = near_breach_window,\n    y = exposure_risk_level,\n    fill = n\n  )\n) +\n  geom_tile(\n    colour = \"white\",\n    linewidth = 0.6\n  ) +\n  geom_text(\n    aes(label = n),\n    size = 4,\n    colour = \"black\"\n  ) +\n  scale_fill_gradient(\n    low = \"#dbe9f6\",\n    high = \"#08306b\"\n  ) +\n  labs(\n    title = \"Exposure-risk Communication Across Breach Windows\",\n    subtitle = \"Comparing communication exposure levels before the embargo breach\",\n    x = \"Breach Window\",\n    y = \"Exposure-risk Level\",\n    fill = \"Messages\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    axis.text.x = element_text(angle = 0),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex02_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## ![](images/Observation.png){width=\"31\"} Observations\n\n-  Controlled exposure communication accounted for the largest communication volume across both the normal and critical periods, increasing from 201 messages during the normal period to 237 messages during the critical breach period.\n\n-  Low exposure communication activity also increased noticeably during the critical period, rising from 90 messages in the normal period to 138 messages near the breach.\n\n-  Although high exposure communication represented a smaller proportion of total communication activity, it remained consistently present across all breach windows, with 29 messages recorded during the normal period and 33 messages during the critical period.\n\n-  The critical breach period exhibited higher communication activity across most exposure-risk categories, suggesting that the inappropriate release was preceded by broader communication escalation rather than a single isolated high-risk interaction.\n\n-   Moderate and high exposure communication behaviour was already observable before the critical breach window, which may indicate that earlier warning signs existed but were not sufficiently escalated into preventive action.\n\n:::\n\n## 4.3 Which Communication Relationships Became More Concentrated Near the Breach?\n\nThis section investigates whether high-risk communication activity became increasingly concentrated among specific sender-recipient relationships prior to the embargo breach on June 5, 2046.\n\nThe analysis focuses on identifying repeated high-risk communication pathways, recurring coordination behaviour, and communication relationships associated with elevated behavioural risk signals.\n\nThese interaction patterns may provide early indications of concentrated coordination activity or communication routes that contributed to embargo-sensitive information bypassing normal containment controls.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_high_risk_flows <- communication_edges_weighted %>%\n  filter(\n    risk_signal_group == \"High Signal\"\n  ) %>%\n  arrange(desc(weight)) %>%\n  slice_head(n = 8) %>%\n  mutate(\n    source = str_replace_all(source, \"_agent\", \"\"),\n    target = str_replace_all(target, \"_agent\", \"\"),\n    source = str_replace_all(source, \"_\", \" \"),\n    target = str_replace_all(target, \"_\", \" \"),\n    source = str_to_title(source),\n    target = str_to_title(target)\n  )\n\nggplot(\n  top_high_risk_flows,\n  aes(\n    axis1 = source,\n    axis2 = target,\n    y = weight\n  )\n) +\n  geom_alluvium(\n    aes(fill = risk_signal_group),\n    width = 1/12,\n    alpha = 0.8\n  ) +\n  geom_stratum(\n    width = 1/12,\n    fill = \"grey90\",\n    colour = \"grey40\"\n  ) +\n  geom_text(\n    stat = \"stratum\",\n    aes(label = after_stat(stratum)),\n    size = 3\n  ) +\n  scale_x_discrete(\n    limits = c(\"Source\", \"Target\"),\n    expand = c(.1, .1)\n  ) +\n  labs(\n    title = \"High-risk Communication Pathways Prior to the Embargo Breach\",\n    subtitle = \"Repeated high-risk sender-recipient pathways by interaction frequency\",\n    x = \"\",\n    y = \"Interaction Frequency\",\n    fill = \"Risk Signal\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    legend.position = \"bottom\"\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex02_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## ![](images/Observation.png){width=\"31\"} Observations\n\n-   High-risk communication behaviour became increasingly concentrated among a relatively small number of sender-recipient pathways prior to the embargo breach.\n\n-   Legal and Social Media emerged as the primary sources of repeated high-risk communication activity, suggesting that communication surrounding embargo-sensitive information became increasingly concentrated within these operational pathways approaching the critical breach period.\n\n-   PR and Platform Trust received substantial volumes of repeated high-risk communication flow, suggesting that communication surrounding embargo-sensitive information became increasingly concentrated within a small number of communication routes.\n\n-   The repeated high-risk interaction patterns observed among a limited group of participants suggest that the inappropriate release was likely preceded by ongoing coordination behaviour rather than isolated one-off communication events.\n\n-   The growing concentration of elevated-risk communication pathways prior to the embargo breach may indicate weakening communication controls and increasing vulnerability within the broader communication environment.\n\n:::\n\n## 4.4 How Did the Critical-period High-risk Communication Network Form?\n\nThis section explores how high-risk communication relationships evolved during the critical breach period approaching the embargo violation on June 5, 2046.\n\nRather than visualising the entire communication system, the analysis focuses specifically on repeated high-risk communication pathways observed near the breach. This helps identify whether communication behaviour became increasingly concentrated among a smaller group of communication participants during the critical period.\n\nBy examining the structure of the high-risk communication network, this section aims to identify repeated coordination pathways, influential communication participants, and interaction patterns that may have contributed to embargo-sensitive information bypassing normal communication controls.\n\n### High-risk Communication Cluster Evolution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncritical_high_risk_edges <- communication_edges %>%\n  filter(\n    risk_signal_group == \"High Signal\",\n    as.Date(timestamp) >= as.Date(\"2046-06-03\")\n  ) %>%\n  count(\n    source,\n    target,\n    name = \"weight\"\n  ) %>%\n  arrange(desc(weight)) %>%\n  slice_head(n = 25) %>%\n  mutate(\n    source_label = source %>%\n      str_replace_all(\"_agent\", \"\") %>%\n      str_replace_all(\"_\", \" \") %>%\n      str_to_title(),\n    target_label = target %>%\n      str_replace_all(\"_agent\", \"\") %>%\n      str_replace_all(\"_\", \" \") %>%\n      str_to_title()\n  )\n\nvis_nodes <- tibble(\n  id = unique(c(\n    critical_high_risk_edges$source_label,\n    critical_high_risk_edges$target_label\n  ))\n) %>%\n  mutate(\n    label = id,\n    group = case_when(\n      str_detect(str_to_lower(id), \"legal\") ~ \"Legal\",\n      str_detect(str_to_lower(id), \"social\") ~ \"Social Media\",\n      str_detect(str_to_lower(id), \"pr\") ~ \"PR\",\n      str_detect(str_to_lower(id), \"platform|trust\") ~ \"Platform Trust\",\n      TRUE ~ \"Other\"\n    ),\n    value = 20\n  )\n\nvis_edges <- critical_high_risk_edges %>%\n  transmute(\n    from = source_label,\n    to = target_label,\n    value = weight,\n    title = paste(\"Interaction Frequency:\", weight),\n    arrows = \"to\"\n  )\n\nvisNetwork(\n  vis_nodes,\n  vis_edges,\n  height = \"600px\",\n  width = \"100%\"\n) %>%\n  visGroups(groupname = \"Legal\", color = \"#fb8072\") %>%\n  visGroups(groupname = \"Social Media\", color = \"#80b1d3\") %>%\n  visGroups(groupname = \"PR\", color = \"#b3de69\") %>%\n  visGroups(groupname = \"Platform Trust\", color = \"#bebada\") %>%\n  visGroups(groupname = \"Other\", color = \"#d9d9d9\") %>%\n  visEdges(\n    smooth = TRUE,\n    color = list(color = \"#cb181d\", opacity = 0.55)\n  ) %>%\n  visOptions(\n    highlightNearest = TRUE,\n    nodesIdSelection = TRUE\n  ) %>%\n  visInteraction(\n    navigationButtons = TRUE,\n    dragNodes = TRUE,\n    zoomView = TRUE\n  ) %>%\n  visLayout(randomSeed = 608)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-1fbf64af66e92c2eb370\" style=\"width:100%;height:600px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-1fbf64af66e92c2eb370\">{\"x\":{\"nodes\":{\"id\":[\"Social Media\",\"Legal\",\"Quality\",\"Pr\",\"Pr Intern\",\"Judge\",\"Social Manager\",\"Platform Trust\",\"Intern\"],\"label\":[\"Social Media\",\"Legal\",\"Quality\",\"Pr\",\"Pr Intern\",\"Judge\",\"Social Manager\",\"Platform Trust\",\"Intern\"],\"group\":[\"Social Media\",\"Legal\",\"Other\",\"PR\",\"PR\",\"Other\",\"Social Media\",\"Platform Trust\",\"Other\"],\"value\":[20,20,20,20,20,20,20,20,20]},\"edges\":{\"from\":[\"Social Media\",\"Legal\",\"Social Media\",\"Legal\",\"Legal\",\"Social Media\",\"Quality\",\"Quality\",\"Quality\",\"Pr\",\"Pr\",\"Pr\",\"Legal\",\"Pr Intern\",\"Social Media\",\"Pr Intern\",\"Quality\",\"Judge\",\"Legal\",\"Pr\",\"Pr Intern\"],\"to\":[\"Legal\",\"Pr\",\"Pr\",\"Social Manager\",\"Platform Trust\",\"Platform Trust\",\"Pr\",\"Social Manager\",\"Legal\",\"Legal\",\"Platform Trust\",\"Social Manager\",\"Pr Intern\",\"Social Manager\",\"Pr Intern\",\"Pr\",\"Pr Intern\",\"Legal\",\"Judge\",\"Intern\",\"Intern\"],\"value\":[38,36,36,35,33,33,10,8,7,5,5,5,4,4,4,3,2,1,1,1,1],\"title\":[\"Interaction Frequency: 38\",\"Interaction Frequency: 36\",\"Interaction Frequency: 36\",\"Interaction Frequency: 35\",\"Interaction Frequency: 33\",\"Interaction Frequency: 33\",\"Interaction Frequency: 10\",\"Interaction Frequency: 8\",\"Interaction Frequency: 7\",\"Interaction Frequency: 5\",\"Interaction Frequency: 5\",\"Interaction Frequency: 5\",\"Interaction Frequency: 4\",\"Interaction Frequency: 4\",\"Interaction Frequency: 4\",\"Interaction Frequency: 3\",\"Interaction Frequency: 2\",\"Interaction Frequency: 1\",\"Interaction Frequency: 1\",\"Interaction Frequency: 1\",\"Interaction Frequency: 1\"],\"arrows\":[\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\",\"to\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\"},\"manipulation\":{\"enabled\":false},\"groups\":{\"Legal\":{\"color\":\"#fb8072\"},\"Social Media\":{\"color\":\"#80b1d3\"},\"PR\":{\"color\":\"#b3de69\"},\"Platform Trust\":{\"color\":\"#bebada\"},\"useDefaultGroups\":true,\"Other\":{\"color\":\"#d9d9d9\"}},\"edges\":{\"color\":{\"color\":\"#cb181d\",\"opacity\":0.55},\"smooth\":true},\"interaction\":{\"dragNodes\":true,\"navigationButtons\":true,\"zoomView\":true,\"zoomSpeed\":1},\"layout\":{\"randomSeed\":608}},\"groups\":[\"Social Media\",\"Legal\",\"Other\",\"PR\",\"Platform Trust\"],\"width\":\"100%\",\"height\":\"600px\",\"idselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"tooltipStay\":300,\"tooltipStyle\":\"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n::: callout-note\n## ![](images/Observation.png){width=\"31\"} Observations\n\n-   High-risk communication activity became noticeably more concentrated within a smaller group of communication participants during the critical breach period, indicating that elevated-risk interactions were no longer spread evenly across the broader communication environment.\n\n-   Legal, PR, Social Media, and Platform Trust appeared repeatedly within the core high-risk communication cluster, suggesting that embargo-sensitive discussions became increasingly concentrated within a closely connected operational communication network during the critical breach period.\n\n-   Multiple communication channels displayed significantly thicker directional flows, especially among those involved in Legal, PR, and Social Media sectors. This indicates ongoing and consistent coordination actions instead of isolated, one-time communication interactions.\n\n-   Communication participants such as Intern and Judge remained comparatively less connected to the central high-risk communication cluster,indicating that the elevated-risk communication behavior was primarily focused within a more limited group of operationally engaged participants rather than across the wider communication system.\n\n-   The dense concentration of repeated high-risk communication pathways during the critical breach period suggests that communication containment might have deteriorated slowly, enabling embargo-sensitive information to flow through more interconnected communication networks.\n\n:::\n\n## 4.5 Did Earlier Elevated-risk Communication Patterns Exist Before the Critical Breach Period?\n\nThis section investigates whether earlier elevated-risk communication patterns were already present before the critical breach period on June 5, 2046.\n\nInstead of focusing only on final high-risk communication behaviour, the analysis compares selected warning indicators before and during the critical period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwarning_indicator_summary <- communications_clean %>%\n  mutate(\n    communication_date = as.Date(timestamp),\n    \n    breach_period = case_when(\n      communication_date < as.Date(\"2046-06-03\") ~ \"Before Critical Period\",\n      TRUE ~ \"Critical Period\"\n    )\n  ) %>%\n  group_by(breach_period) %>%\n  summarise(\n    `Moderate-risk communications` = sum(\n      risk_signal_group == \"Moderate Signal\",\n      na.rm = TRUE\n    ),\n    \n    `High-risk communications` = sum(\n      risk_signal_group == \"High Signal\",\n      na.rm = TRUE\n    ),\n    \n    `Moderate + high-risk communications` =\n      `Moderate-risk communications` + `High-risk communications`,\n    \n    `Public / side-channel communications` = sum(\n      communication_scope %in% c(\"Public\", \"Side-channel\"),\n      na.rm = TRUE\n    ),\n    \n    .groups = \"drop\"\n  ) %>%\n  complete(\n    breach_period = c(\n      \"Before Critical Period\",\n      \"Critical Period\"\n    ),\n    fill = list(\n      `Moderate-risk communications` = 0,\n      `High-risk communications` = 0,\n      `Moderate + high-risk communications` = 0,\n      `Public / side-channel communications` = 0\n    )\n  ) %>%\n  pivot_longer(\n    cols = -breach_period,\n    names_to = \"warning_indicator\",\n    values_to = \"count\"\n  ) %>%\n  mutate(\n    breach_period = factor(\n      breach_period,\n      levels = c(\n        \"Before Critical Period\",\n        \"Critical Period\"\n      )\n    ),\n    \n    warning_indicator = factor(\n      warning_indicator,\n      levels = c(\n        \"Public / side-channel communications\",\n        \"Moderate-risk communications\",\n        \"High-risk communications\",\n        \"Moderate + high-risk communications\"\n      )\n    )\n  )\n\nggplot(\n  warning_indicator_summary,\n  aes(\n    x = warning_indicator,\n    y = count,\n    fill = breach_period\n  )\n) +\n  geom_col(\n    position = position_dodge(width = 0.75),\n    width = 0.65\n  ) +\n  geom_text(\n    aes(label = scales::comma(count)),\n    position = position_dodge(width = 0.75),\n    hjust = -0.15,\n    size = 3\n  ) +\n  coord_flip() +\n  scale_fill_manual(\n    values = c(\n      \"Before Critical Period\" = \"#737373\",\n      \"Critical Period\" = \"#cb181d\"\n    )\n  ) +\n  scale_y_continuous(\n    expand = expansion(mult = c(0, 0.18))\n  ) +\n  labs(\n    title = \"Early Warning Indicators Before and During the Critical Period\",\n    subtitle = \"Comparing elevated-risk signals before and near the breach\",\n    x = \"\",\n    y = \"Number of Communications\",\n    fill = \"Breach Period\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    legend.position = \"bottom\"\n  )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex02_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nTo quantify the visual comparison, the warning indicators are summarised below to show the scale of escalation from the earlier period to the critical breach period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwarning_escalation_summary <- warning_indicator_summary %>%\n  select(\n    breach_period,\n    warning_indicator,\n    count\n  ) %>%\n  pivot_wider(\n    names_from = breach_period,\n    values_from = count,\n    values_fill = 0\n  ) %>%\n  mutate(\n    `Increase` = `Critical Period` - `Before Critical Period`,\n    \n    `Escalation Multiplier` = if_else(\n      `Before Critical Period` == 0,\n      NA_real_,\n      `Critical Period` / `Before Critical Period`\n    ),\n    \n    `Escalation Multiplier` = case_when(\n      is.na(`Escalation Multiplier`) ~ \"New signal\",\n      TRUE ~ paste0(round(`Escalation Multiplier`, 1), \"x\")\n    ),\n    \n    `Analytical Interpretation` = case_when(\n      warning_indicator == \"High-risk communications\" ~\n        \"Severe risk signals intensified sharply during the critical period.\",\n      \n      warning_indicator == \"Moderate + high-risk communications\" ~\n        \"Overall elevated-risk behaviour was present earlier but escalated strongly near the breach.\",\n      \n      warning_indicator == \"Moderate-risk communications\" ~\n        \"Earlier moderate warning signs existed but became more pronounced during the critical period.\",\n      \n      warning_indicator == \"Public / side-channel communications\" ~\n        \"Communication exposure increased, suggesting weaker containment near the breach.\",\n      \n      TRUE ~ \"Review required.\"\n    )\n  ) %>%\n  arrange(desc(`Critical Period`))\n\nwarning_escalation_summary %>%\n  rename(\n    `Warning Indicator` = warning_indicator\n  ) %>%\n  knitr::kable(\n    caption = \"Warning indicator escalation summary before and during the critical breach period\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Warning indicator escalation summary before and during the critical breach period\n\n|Warning Indicator                    | Before Critical Period| Critical Period| Increase|Escalation Multiplier |Analytical Interpretation                                                                     |\n|:------------------------------------|----------------------:|---------------:|--------:|:---------------------|:---------------------------------------------------------------------------------------------|\n|Moderate + high-risk communications  |                     49|             337|      288|6.9x                  |Overall elevated-risk behaviour was present earlier but escalated strongly near the breach.   |\n|High-risk communications             |                      9|             193|      184|21.4x                 |Severe risk signals intensified sharply during the critical period.                           |\n|Moderate-risk communications         |                     40|             144|      104|3.6x                  |Earlier moderate warning signs existed but became more pronounced during the critical period. |\n|Public / side-channel communications |                     44|             132|       88|3x                    |Communication exposure increased, suggesting weaker containment near the breach.              |\n\n\n:::\n:::\n\n\n::: callout-note\n## ![](images/Observation.png){width=\"31\"} Observations\n\n-   Prior elevated-risk communication patterns existed before the critical breach timeframe, with 49 moderate-to-high risk communications recorded before June 3, 2046. This suggests that warning signs existed earlier, but at a much lower level.\n\n-   The critical period demonstrated a significant rise in elevated-risk communication, jumping from 49 to 337 moderate-to-high risk communications. This signifies a 6.9 times increase, showing that risk signals became significantly more apparent close to the breach.  \n\n-   High-risk communication showed the strongest increase, rising from 9 earlier high-risk communications to 193 during the critical period. This 21.4 times increase suggests that severe communication risk intensified rapidly close to the inappropriate release.\n\n-   Public and side-channel communication increased from 44 to 132 communications, indicating that communication risk was increasing in both volume and exposure within less-contained communication contexts.\n\n-   Overall, the findings suggest that earlier warning signs were present but likely appeared too limited or insufficiently severe to trigger stronger intervention. The critical period marked a clear escalation where elevated-risk behaviour became much harder to ignore.\n:::\n\n## 4.6 What Warning Evidence Emerged Before the Network Reconstruction?\n\nThis section consolidates the key behavioural and communication warning evidence identified from the exploratory analysis. Instead of presenting an additional independent visual, the analysis summarises how communication activity, behavioural risk signals, communication environments, high-risk pathways, and warning indicators changed prior to the embargo breach.\n\nThis provides an interim evidence base before moving into the detailed network reconstruction in Section 5.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsection4_evidence_summary <- tibble(\n  `Analytical Area` = c(\n    \"Communication escalation\",\n    \"Behavioural risk escalation\",\n    \"Communication environment shift\",\n    \"Exposure-risk behaviour\",\n    \"High-risk communication pathways\",\n    \"Critical-period high-risk network\",\n    \"Earlier warning indicators\"\n  ),\n  \n  `Key Evidence from Section 4` = c(\n    \"Daily communication activity remained relatively stable at around 25–40 messages per day before rising sharply to more than 500 communications on June 5, 2046.\",\n    \n    \"Moderate-risk and high-risk communication signals increased substantially during the critical breach period, suggesting that communication behaviour became more abnormal near the inappropriate release.\",\n    \n    \"Internal group communication remained dominant, but its share declined from approximately 61% during the normal period to 46% during the critical period, while side-channel communication increased from about 4% to 19%.\",\n    \n    \"Controlled exposure and low exposure communications increased during the critical period, while moderate and high exposure behaviour was already observable before the breach window.\",\n    \n    \"Repeated high-risk sender-recipient pathways became concentrated among a smaller number of communication routes, particularly involving Legal, Social Media, PR, and Platform Trust.\",\n    \n    \"The critical-period network showed a dense high-risk communication cluster involving Legal, PR, Social Media, and Platform Trust, with thicker directional flows suggesting repeated coordination behaviour.\",\n    \n    \"Earlier warning indicators existed before June 3, 2046, but were much weaker. Moderate-to-high risk communications increased from 49 before the critical period to 337 during the critical period.\"\n  ),\n  \n  `How It Supports the MC1 Investigation` = c(\n    \"Supports the presence of abnormal communication escalation before the embargo breach.\",\n    \n    \"Provides evidence that the inappropriate release was preceded by observable behavioural warning signals.\",\n    \n    \"Suggests weakening communication containment as activity became more distributed across less-contained communication environments.\",\n    \n    \"Indicates that exposure-related communication risk was not entirely new, but became more pronounced close to the breach.\",\n    \n    \"Identifies relationship-level communication pathways that may have supported information propagation.\",\n    \n    \"Highlights the key communication cluster that should be examined more closely in the Section 5 network reconstruction.\",\n    \n    \"Helps explain why prior warning signs may not have triggered action: earlier signals existed, but appeared less severe than the critical-period escalation.\"\n  )\n)\n\nsection4_evidence_summary %>%\n  knitr::kable(\n    caption = \"Interim evidence summary from Section 4 exploratory communication and behaviour analysis\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Interim evidence summary from Section 4 exploratory communication and behaviour analysis\n\n|Analytical Area                   |Key Evidence from Section 4                                                                                                                                                                                                |How It Supports the MC1 Investigation                                                                                                                       |\n|:---------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------|\n|Communication escalation          |Daily communication activity remained relatively stable at around 25–40 messages per day before rising sharply to more than 500 communications on June 5, 2046.                                                            |Supports the presence of abnormal communication escalation before the embargo breach.                                                                       |\n|Behavioural risk escalation       |Moderate-risk and high-risk communication signals increased substantially during the critical breach period, suggesting that communication behaviour became more abnormal near the inappropriate release.                  |Provides evidence that the inappropriate release was preceded by observable behavioural warning signals.                                                    |\n|Communication environment shift   |Internal group communication remained dominant, but its share declined from approximately 61% during the normal period to 46% during the critical period, while side-channel communication increased from about 4% to 19%. |Suggests weakening communication containment as activity became more distributed across less-contained communication environments.                          |\n|Exposure-risk behaviour           |Controlled exposure and low exposure communications increased during the critical period, while moderate and high exposure behaviour was already observable before the breach window.                                      |Indicates that exposure-related communication risk was not entirely new, but became more pronounced close to the breach.                                    |\n|High-risk communication pathways  |Repeated high-risk sender-recipient pathways became concentrated among a smaller number of communication routes, particularly involving Legal, Social Media, PR, and Platform Trust.                                       |Identifies relationship-level communication pathways that may have supported information propagation.                                                       |\n|Critical-period high-risk network |The critical-period network showed a dense high-risk communication cluster involving Legal, PR, Social Media, and Platform Trust, with thicker directional flows suggesting repeated coordination behaviour.               |Highlights the key communication cluster that should be examined more closely in the Section 5 network reconstruction.                                      |\n|Earlier warning indicators        |Earlier warning indicators existed before June 3, 2046, but were much weaker. Moderate-to-high risk communications increased from 49 before the critical period to 337 during the critical period.                         |Helps explain why prior warning signs may not have triggered action: earlier signals existed, but appeared less severe than the critical-period escalation. |\n\n\n:::\n:::\n\n\n### Interim finding\n\n::: callout-note\n## ![](images/Observation.png){width=\"31\"} Interim Finding\n\n-   The exploratory analysis suggests that the inappropriate release was not preceded by a single isolated signal. Instead, several warning patterns emerged across communication volume, behavioural risk signals, communication environments, high-risk pathways, and earlier warning indicators.\n\n-   However, the earlier warning signs appeared weaker and less concentrated than the escalation observed during the critical breach period. This may explain why prior occasions did not result in stronger intervention or containment action.\n\n-   The next section therefore moves from behavioural evidence into network reconstruction to examine how communication relationships and pathways may have contributed to the embargo-sensitive post bypassing enforcement controls.\n:::",
    "supporting": [
      "Take-Home_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/vis-9.1.0/vis-network.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/vis-9.1.0/vis-network.min.js\"></script>\n<script src=\"../../site_libs/visNetwork-binding-2.1.4/visNetwork.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}